### ISSUE TITLE
Some option interpreted as TupleType

### ISSUE THREAD

**Issue by joetsoi** [afilip1/ronfmt#5]
I have this ron
```
Locations(
    locations: [
        (
            kind: Lair,
            image: Some(
                Image(
                    sheet: "mi.c",
                    image: 20,
                    x: 0,
                    y: 0,
                    image_type: Collidee,
                ),
            ),
...
```
Which is resulting in this invalid ron `Some(Image(), )`  see
https://github.com/ron-rs/ron/blob/master/docs/grammar.md#optional
```
option = "Some", ws, "(", ws, value, ws, ")";
```

After a quick glance, I suspect this is the result of interpreting `Some` as a `TupleType`, which means when it is displayed, it is formatted using https://github.com/afilip1/ronfmt/blob/6ac02e08ddeb875b418b33947d71572b69d703a4/src/ast/display.rs#L111
note the trailing comma. in https://github.com/afilip1/ronfmt/blob/6ac02e08ddeb875b418b33947d71572b69d703a4/src/ast/display.rs#L47

If I'm reading this correctly then Optional values should be handled as a separate case from the Tuple type?

happy to look into this further if this is still alive enough to accept pull requests

**Comment by afilip1** [comment]
Hi! Thank you for reaching out.

I'm terribly sorry for the late response. The development of ronfmt stalled as I ran into some issues I had trouble resolving (namely with comment formatting), and I suspect would require sizeable architectural changes and investment of effort that I'm not currently willing to provide. I'll keep your report in mind if I ever come back to it, but for all intents and purposes this project is frozen indefinitely. Apologies for the inconvenience this might have caused. Feel free to fork the project or use it as reference if you'd like to continue where I left off.

**Comment by joetsoi** [comment]
No problem! It's useful to me even in the current state, I've started a fork and was planning on making some improvements where I can, but of course, like you, we all have limited time. So totally understand the late response etc.
